name: Project Automation

on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled, assigned, unassigned]
  pull_request:
    types:
      [
        opened,
        closed,
        reopened,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        review_requested,
        review_request_removed,
      ]

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project Board
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move to In Progress
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-id: ${{ secrets.IN_PROGRESS_COLUMN_ID }}

      - name: Move to Review
        if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-id: ${{ secrets.REVIEW_COLUMN_ID }}

      - name: Move to Done
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-id: ${{ secrets.DONE_COLUMN_ID }}
