name: Project Automation

on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled, assigned, unassigned]
  pull_request:
    types:
      [
        opened,
        closed,
        reopened,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        review_requested,
        review_request_removed,
      ]

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project Board
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
